// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(demucsFFI)
import demucsFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_demucs_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_demucs_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureDemucsInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterFloat: FfiConverterPrimitive {
    typealias FfiType = Float
    typealias SwiftType = Float

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Float {
        return try lift(readFloat(&buf))
    }

    public static func write(_ value: Float, into buf: inout [UInt8]) {
        writeFloat(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Thread-safe HTDemucs source-separation engine.
 *
 * Typical lifecycle from Swift:
 * ```swift
 * configureCacheDir(path: appSupportDir)          // sandboxed platforms
 * try await downloadModel(model: .fourStem, listener: dl)
 * let engine = DemucsEngine()
 * let secs = try await engine.loadModel(model: .fourStem)
 * try await engine.warmup()
 * let stems = try await engine.separate(left: l, right: r, sampleRate: 44100)
 * ```
 */
public protocol DemucsEngineProtocol: AnyObject, Sendable {
    
    func isLoaded() async  -> Bool
    
    /**
     * Load a model's weights from the local cache into memory (and onto the
     * GPU device). Errors with `NotCached` if `downloadModel` has not been
     * run for this model. Returns the wall-clock load time in seconds.
     */
    func loadModel(model: DemucsModel) async throws  -> Double
    
    /**
     * The model currently loaded, if any.
     */
    func loadedModel() async  -> DemucsModel?
    
    /**
     * Separate a stereo track into stems.
     *
     * `left` and `right` are per-channel PCM samples (any sample rate;
     * resampled to 44100 Hz internally). Mono input: pass the same samples
     * for both channels. Output stems are stereo PCM at 44100 Hz.
     *
     * Holds the engine lock for the whole separation, so concurrent calls
     * on one engine serialize.
     */
    func separate(left: [Float], right: [Float], sampleRate: UInt32) async throws  -> [StemResult]
    
    /**
     * Drop the loaded model, freeing CPU and GPU memory. Returns true if a
     * model was loaded.
     */
    func unloadModel() async  -> Bool
    
    /**
     * Run the full pipeline once on synthetic audio to pre-compile GPU
     * shaders and resolve autotune. Optional but recommended before the
     * first `separate` call; takes a few seconds on first run.
     */
    func warmup() async throws 
    
}
/**
 * Thread-safe HTDemucs source-separation engine.
 *
 * Typical lifecycle from Swift:
 * ```swift
 * configureCacheDir(path: appSupportDir)          // sandboxed platforms
 * try await downloadModel(model: .fourStem, listener: dl)
 * let engine = DemucsEngine()
 * let secs = try await engine.loadModel(model: .fourStem)
 * try await engine.warmup()
 * let stems = try await engine.separate(left: l, right: r, sampleRate: 44100)
 * ```
 */
open class DemucsEngine: DemucsEngineProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_demucs_fn_clone_demucsengine(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
    uniffi_demucs_fn_constructor_demucsengine_new($0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_demucs_fn_free_demucsengine(handle, $0) }
    }

    

    
open func isLoaded()async  -> Bool  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_demucs_fn_method_demucsengine_is_loaded(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_demucs_rust_future_poll_i8,
            completeFunc: ffi_demucs_rust_future_complete_i8,
            freeFunc: ffi_demucs_rust_future_free_i8,
            liftFunc: FfiConverterBool.lift,
            errorHandler: nil
            
        )
}
    
    /**
     * Load a model's weights from the local cache into memory (and onto the
     * GPU device). Errors with `NotCached` if `downloadModel` has not been
     * run for this model. Returns the wall-clock load time in seconds.
     */
open func loadModel(model: DemucsModel)async throws  -> Double  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_demucs_fn_method_demucsengine_load_model(
                    self.uniffiCloneHandle(),
                    FfiConverterTypeDemucsModel_lower(model)
                )
            },
            pollFunc: ffi_demucs_rust_future_poll_f64,
            completeFunc: ffi_demucs_rust_future_complete_f64,
            freeFunc: ffi_demucs_rust_future_free_f64,
            liftFunc: FfiConverterDouble.lift,
            errorHandler: FfiConverterTypeDemucsFfiError_lift
        )
}
    
    /**
     * The model currently loaded, if any.
     */
open func loadedModel()async  -> DemucsModel?  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_demucs_fn_method_demucsengine_loaded_model(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_demucs_rust_future_poll_rust_buffer,
            completeFunc: ffi_demucs_rust_future_complete_rust_buffer,
            freeFunc: ffi_demucs_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypeDemucsModel.lift,
            errorHandler: nil
            
        )
}
    
    /**
     * Separate a stereo track into stems.
     *
     * `left` and `right` are per-channel PCM samples (any sample rate;
     * resampled to 44100 Hz internally). Mono input: pass the same samples
     * for both channels. Output stems are stereo PCM at 44100 Hz.
     *
     * Holds the engine lock for the whole separation, so concurrent calls
     * on one engine serialize.
     */
open func separate(left: [Float], right: [Float], sampleRate: UInt32)async throws  -> [StemResult]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_demucs_fn_method_demucsengine_separate(
                    self.uniffiCloneHandle(),
                    FfiConverterSequenceFloat.lower(left),FfiConverterSequenceFloat.lower(right),FfiConverterUInt32.lower(sampleRate)
                )
            },
            pollFunc: ffi_demucs_rust_future_poll_rust_buffer,
            completeFunc: ffi_demucs_rust_future_complete_rust_buffer,
            freeFunc: ffi_demucs_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeStemResult.lift,
            errorHandler: FfiConverterTypeDemucsFfiError_lift
        )
}
    
    /**
     * Drop the loaded model, freeing CPU and GPU memory. Returns true if a
     * model was loaded.
     */
open func unloadModel()async  -> Bool  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_demucs_fn_method_demucsengine_unload_model(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_demucs_rust_future_poll_i8,
            completeFunc: ffi_demucs_rust_future_complete_i8,
            freeFunc: ffi_demucs_rust_future_free_i8,
            liftFunc: FfiConverterBool.lift,
            errorHandler: nil
            
        )
}
    
    /**
     * Run the full pipeline once on synthetic audio to pre-compile GPU
     * shaders and resolve autotune. Optional but recommended before the
     * first `separate` call; takes a few seconds on first run.
     */
open func warmup()async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_demucs_fn_method_demucsengine_warmup(
                    self.uniffiCloneHandle()
                    
                )
            },
            pollFunc: ffi_demucs_rust_future_poll_void,
            completeFunc: ffi_demucs_rust_future_complete_void,
            freeFunc: ffi_demucs_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeDemucsFfiError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDemucsEngine: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = DemucsEngine

    public static func lift(_ handle: UInt64) throws -> DemucsEngine {
        return DemucsEngine(unsafeFromHandle: handle)
    }

    public static func lower(_ value: DemucsEngine) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DemucsEngine {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: DemucsEngine, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDemucsEngine_lift(_ handle: UInt64) throws -> DemucsEngine {
    return try FfiConverterTypeDemucsEngine.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDemucsEngine_lower(_ value: DemucsEngine) -> UInt64 {
    return FfiConverterTypeDemucsEngine.lower(value)
}




/**
 * Progress payload for weight downloads.
 */
public struct DownloadProgress: Equatable, Hashable {
    public var downloadedBytes: UInt64
    /**
     * 0 when the server did not report a Content-Length.
     */
    public var totalBytes: UInt64
    /**
     * 0.0–1.0, or 0.0 when the total is unknown.
     */
    public var fraction: Double
    public var done: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(downloadedBytes: UInt64, 
        /**
         * 0 when the server did not report a Content-Length.
         */totalBytes: UInt64, 
        /**
         * 0.0–1.0, or 0.0 when the total is unknown.
         */fraction: Double, done: Bool) {
        self.downloadedBytes = downloadedBytes
        self.totalBytes = totalBytes
        self.fraction = fraction
        self.done = done
    }

    

    
}

#if compiler(>=6)
extension DownloadProgress: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDownloadProgress: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DownloadProgress {
        return
            try DownloadProgress(
                downloadedBytes: FfiConverterUInt64.read(from: &buf), 
                totalBytes: FfiConverterUInt64.read(from: &buf), 
                fraction: FfiConverterDouble.read(from: &buf), 
                done: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: DownloadProgress, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.downloadedBytes, into: &buf)
        FfiConverterUInt64.write(value.totalBytes, into: &buf)
        FfiConverterDouble.write(value.fraction, into: &buf)
        FfiConverterBool.write(value.done, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDownloadProgress_lift(_ buf: RustBuffer) throws -> DownloadProgress {
    return try FfiConverterTypeDownloadProgress.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDownloadProgress_lower(_ value: DownloadProgress) -> RustBuffer {
    return FfiConverterTypeDownloadProgress.lower(value)
}


/**
 * Descriptive metadata for a model variant.
 */
public struct ModelMetadata: Equatable, Hashable {
    public var id: String
    public var label: String
    public var description: String
    /**
     * Safetensors weight file name, e.g. "htdemucs.safetensors".
     */
    public var filename: String
    public var sizeMb: UInt32
    public var stems: [StemKind]
    public var downloadUrl: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, label: String, description: String, 
        /**
         * Safetensors weight file name, e.g. "htdemucs.safetensors".
         */filename: String, sizeMb: UInt32, stems: [StemKind], downloadUrl: String) {
        self.id = id
        self.label = label
        self.description = description
        self.filename = filename
        self.sizeMb = sizeMb
        self.stems = stems
        self.downloadUrl = downloadUrl
    }

    

    
}

#if compiler(>=6)
extension ModelMetadata: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeModelMetadata: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ModelMetadata {
        return
            try ModelMetadata(
                id: FfiConverterString.read(from: &buf), 
                label: FfiConverterString.read(from: &buf), 
                description: FfiConverterString.read(from: &buf), 
                filename: FfiConverterString.read(from: &buf), 
                sizeMb: FfiConverterUInt32.read(from: &buf), 
                stems: FfiConverterSequenceTypeStemKind.read(from: &buf), 
                downloadUrl: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ModelMetadata, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.label, into: &buf)
        FfiConverterString.write(value.description, into: &buf)
        FfiConverterString.write(value.filename, into: &buf)
        FfiConverterUInt32.write(value.sizeMb, into: &buf)
        FfiConverterSequenceTypeStemKind.write(value.stems, into: &buf)
        FfiConverterString.write(value.downloadUrl, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModelMetadata_lift(_ buf: RustBuffer) throws -> ModelMetadata {
    return try FfiConverterTypeModelMetadata.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeModelMetadata_lower(_ value: ModelMetadata) -> RustBuffer {
    return FfiConverterTypeModelMetadata.lower(value)
}


/**
 * Coarse separation progress derived from chunk/stem counters.
 */
public struct SeparationProgress: Equatable, Hashable {
    /**
     * 0.0–1.0 overall fraction.
     */
    public var fraction: Double
    /**
     * 0-based index of the chunk currently in flight.
     */
    public var currentChunk: UInt64
    public var totalChunks: UInt64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * 0.0–1.0 overall fraction.
         */fraction: Double, 
        /**
         * 0-based index of the chunk currently in flight.
         */currentChunk: UInt64, totalChunks: UInt64) {
        self.fraction = fraction
        self.currentChunk = currentChunk
        self.totalChunks = totalChunks
    }

    

    
}

#if compiler(>=6)
extension SeparationProgress: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSeparationProgress: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SeparationProgress {
        return
            try SeparationProgress(
                fraction: FfiConverterDouble.read(from: &buf), 
                currentChunk: FfiConverterUInt64.read(from: &buf), 
                totalChunks: FfiConverterUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: SeparationProgress, into buf: inout [UInt8]) {
        FfiConverterDouble.write(value.fraction, into: &buf)
        FfiConverterUInt64.write(value.currentChunk, into: &buf)
        FfiConverterUInt64.write(value.totalChunks, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSeparationProgress_lift(_ buf: RustBuffer) throws -> SeparationProgress {
    return try FfiConverterTypeSeparationProgress.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSeparationProgress_lower(_ value: SeparationProgress) -> RustBuffer {
    return FfiConverterTypeSeparationProgress.lower(value)
}


/**
 * One separated stem: interleaved-free stereo PCM at 44100 Hz.
 */
public struct StemResult: Equatable, Hashable {
    public var kind: StemKind
    public var left: [Float]
    public var right: [Float]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(kind: StemKind, left: [Float], right: [Float]) {
        self.kind = kind
        self.left = left
        self.right = right
    }

    

    
}

#if compiler(>=6)
extension StemResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStemResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StemResult {
        return
            try StemResult(
                kind: FfiConverterTypeStemKind.read(from: &buf), 
                left: FfiConverterSequenceFloat.read(from: &buf), 
                right: FfiConverterSequenceFloat.read(from: &buf)
        )
    }

    public static func write(_ value: StemResult, into buf: inout [UInt8]) {
        FfiConverterTypeStemKind.write(value.kind, into: &buf)
        FfiConverterSequenceFloat.write(value.left, into: &buf)
        FfiConverterSequenceFloat.write(value.right, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStemResult_lift(_ buf: RustBuffer) throws -> StemResult {
    return try FfiConverterTypeStemResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStemResult_lower(_ value: StemResult) -> RustBuffer {
    return FfiConverterTypeStemResult.lower(value)
}


/**
 * Errors surfaced across the FFI boundary.
 */
public enum DemucsFfiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case NoModelLoaded
    case AlreadyLoaded(modelId: String
    )
    case Weights(reason: String
    )
    case Dsp(reason: String
    )
    case Tensor(reason: String
    )
    case Internal(reason: String
    )
    case Cancelled
    case NotCached(reason: String
    )
    case Io(reason: String
    )
    case NoCacheDir
    case Download(reason: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension DemucsFfiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDemucsFfiError: FfiConverterRustBuffer {
    typealias SwiftType = DemucsFfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DemucsFfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .NoModelLoaded
        case 2: return .AlreadyLoaded(
            modelId: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Weights(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Dsp(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 5: return .Tensor(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 6: return .Internal(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 7: return .Cancelled
        case 8: return .NotCached(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 9: return .Io(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 10: return .NoCacheDir
        case 11: return .Download(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DemucsFfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .NoModelLoaded:
            writeInt(&buf, Int32(1))
        
        
        case let .AlreadyLoaded(modelId):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(modelId, into: &buf)
            
        
        case let .Weights(reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .Dsp(reason):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .Tensor(reason):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .Internal(reason):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(reason, into: &buf)
            
        
        case .Cancelled:
            writeInt(&buf, Int32(7))
        
        
        case let .NotCached(reason):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .Io(reason):
            writeInt(&buf, Int32(9))
            FfiConverterString.write(reason, into: &buf)
            
        
        case .NoCacheDir:
            writeInt(&buf, Int32(10))
        
        
        case let .Download(reason):
            writeInt(&buf, Int32(11))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDemucsFfiError_lift(_ buf: RustBuffer) throws -> DemucsFfiError {
    return try FfiConverterTypeDemucsFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDemucsFfiError_lower(_ value: DemucsFfiError) -> RustBuffer {
    return FfiConverterTypeDemucsFfiError.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Which HTDemucs variant to load.
 */

public enum DemucsModel: Equatable, Hashable {
    
    /**
     * htdemucs — 4 stems, balanced speed and quality (~84 MB).
     */
    case fourStem
    /**
     * htdemucs_6s — 6 stems, adds guitar and piano (~84 MB).
     */
    case sixStem
    /**
     * htdemucs_ft — fine-tuned, best quality, one sub-model per requested
     * stem so inference time scales with `stems.len()` (~333 MB).
     */
    case fineTuned(stems: [StemKind]
    )





}

#if compiler(>=6)
extension DemucsModel: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDemucsModel: FfiConverterRustBuffer {
    typealias SwiftType = DemucsModel

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DemucsModel {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .fourStem
        
        case 2: return .sixStem
        
        case 3: return .fineTuned(stems: try FfiConverterSequenceTypeStemKind.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DemucsModel, into buf: inout [UInt8]) {
        switch value {
        
        
        case .fourStem:
            writeInt(&buf, Int32(1))
        
        
        case .sixStem:
            writeInt(&buf, Int32(2))
        
        
        case let .fineTuned(stems):
            writeInt(&buf, Int32(3))
            FfiConverterSequenceTypeStemKind.write(stems, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDemucsModel_lift(_ buf: RustBuffer) throws -> DemucsModel {
    return try FfiConverterTypeDemucsModel.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDemucsModel_lower(_ value: DemucsModel) -> RustBuffer {
    return FfiConverterTypeDemucsModel.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * A single separable audio source.
 */

public enum StemKind: Equatable, Hashable {
    
    case drums
    case bass
    case other
    case vocals
    case guitar
    case piano





}

#if compiler(>=6)
extension StemKind: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStemKind: FfiConverterRustBuffer {
    typealias SwiftType = StemKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StemKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .drums
        
        case 2: return .bass
        
        case 3: return .other
        
        case 4: return .vocals
        
        case 5: return .guitar
        
        case 6: return .piano
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: StemKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .drums:
            writeInt(&buf, Int32(1))
        
        
        case .bass:
            writeInt(&buf, Int32(2))
        
        
        case .other:
            writeInt(&buf, Int32(3))
        
        
        case .vocals:
            writeInt(&buf, Int32(4))
        
        
        case .guitar:
            writeInt(&buf, Int32(5))
        
        
        case .piano:
            writeInt(&buf, Int32(6))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStemKind_lift(_ buf: RustBuffer) throws -> StemKind {
    return try FfiConverterTypeStemKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStemKind_lower(_ value: StemKind) -> RustBuffer {
    return FfiConverterTypeStemKind.lower(value)
}





/**
 * Receives download progress. Return true to continue, false to cancel —
 * the partial file is deleted and `download_model` returns `Cancelled`.
 */
public protocol DownloadProgressListener: AnyObject, Sendable {
    
    func onProgress(progress: DownloadProgress)  -> Bool
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceDownloadProgressListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceDownloadProgressListener] = [UniffiVTableCallbackInterfaceDownloadProgressListener(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceDownloadProgressListener.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface DownloadProgressListener: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceDownloadProgressListener.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface DownloadProgressListener: handle missing in uniffiClone")
            }
        },
        onProgress: { (
            uniffiHandle: UInt64,
            progress: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<Int8>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Bool in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceDownloadProgressListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onProgress(
                     progress: try FfiConverterTypeDownloadProgress_lift(progress)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterBool.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitDownloadProgressListener() {
    uniffi_demucs_fn_init_callback_vtable_downloadprogresslistener(UniffiCallbackInterfaceDownloadProgressListener.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceDownloadProgressListener {
    fileprivate static let handleMap = UniffiHandleMap<DownloadProgressListener>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceDownloadProgressListener : FfiConverter {
    typealias SwiftType = DownloadProgressListener
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceDownloadProgressListener_lift(_ handle: UInt64) throws -> DownloadProgressListener {
    return try FfiConverterCallbackInterfaceDownloadProgressListener.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceDownloadProgressListener_lower(_ v: DownloadProgressListener) -> UInt64 {
    return FfiConverterCallbackInterfaceDownloadProgressListener.lower(v)
}




/**
 * Receives coarse progress during separation.
 *
 * Called from the inference task; keep the callback fast. Return true to
 * continue, false to cancel — the engine then returns `Cancelled`.
 */
public protocol SeparationProgressListener: AnyObject, Sendable {
    
    func onProgress(progress: SeparationProgress)  -> Bool
    
}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceSeparationProgressListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceSeparationProgressListener] = [UniffiVTableCallbackInterfaceSeparationProgressListener(
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            do {
                try FfiConverterCallbackInterfaceSeparationProgressListener.handleMap.remove(handle: uniffiHandle)
            } catch {
                print("Uniffi callback interface SeparationProgressListener: handle missing in uniffiFree")
            }
        },
        uniffiClone: { (uniffiHandle: UInt64) -> UInt64 in
            do {
                return try FfiConverterCallbackInterfaceSeparationProgressListener.handleMap.clone(handle: uniffiHandle)
            } catch {
                fatalError("Uniffi callback interface SeparationProgressListener: handle missing in uniffiClone")
            }
        },
        onProgress: { (
            uniffiHandle: UInt64,
            progress: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<Int8>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> Bool in
                guard let uniffiObj = try? FfiConverterCallbackInterfaceSeparationProgressListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onProgress(
                     progress: try FfiConverterTypeSeparationProgress_lift(progress)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterBool.lower($0) }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        }
    )]
}

private func uniffiCallbackInitSeparationProgressListener() {
    uniffi_demucs_fn_init_callback_vtable_separationprogresslistener(UniffiCallbackInterfaceSeparationProgressListener.vtable)
}

// FfiConverter protocol for callback interfaces
#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterCallbackInterfaceSeparationProgressListener {
    fileprivate static let handleMap = UniffiHandleMap<SeparationProgressListener>()
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
extension FfiConverterCallbackInterfaceSeparationProgressListener : FfiConverter {
    typealias SwiftType = SeparationProgressListener
    typealias FfiType = UInt64

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ handle: UInt64) throws -> SwiftType {
        try handleMap.get(handle: handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ v: SwiftType) -> UInt64 {
        return handleMap.insert(obj: v)
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(v))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceSeparationProgressListener_lift(_ handle: UInt64) throws -> SeparationProgressListener {
    return try FfiConverterCallbackInterfaceSeparationProgressListener.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterCallbackInterfaceSeparationProgressListener_lower(_ v: SeparationProgressListener) -> UInt64 {
    return FfiConverterCallbackInterfaceSeparationProgressListener.lower(v)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeDemucsModel: FfiConverterRustBuffer {
    typealias SwiftType = DemucsModel?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeDemucsModel.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeDemucsModel.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceFloat: FfiConverterRustBuffer {
    typealias SwiftType = [Float]

    public static func write(_ value: [Float], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterFloat.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Float] {
        let len: Int32 = try readInt(&buf)
        var seq = [Float]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterFloat.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeModelMetadata: FfiConverterRustBuffer {
    typealias SwiftType = [ModelMetadata]

    public static func write(_ value: [ModelMetadata], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeModelMetadata.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ModelMetadata] {
        let len: Int32 = try readInt(&buf)
        var seq = [ModelMetadata]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeModelMetadata.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeStemResult: FfiConverterRustBuffer {
    typealias SwiftType = [StemResult]

    public static func write(_ value: [StemResult], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeStemResult.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [StemResult] {
        let len: Int32 = try readInt(&buf)
        var seq = [StemResult]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeStemResult.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeStemKind: FfiConverterRustBuffer {
    typealias SwiftType = [StemKind]

    public static func write(_ value: [StemKind], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeStemKind.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [StemKind] {
        let len: Int32 = try readInt(&buf)
        var seq = [StemKind]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeStemKind.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureDemucsInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
/**
 * Metadata for every supported model variant.
 */
public func allModels() -> [ModelMetadata]  {
    return try!  FfiConverterSequenceTypeModelMetadata.lift(try! rustCall() {
    uniffi_demucs_fn_func_all_models($0
    )
})
}
/**
 * Filesystem path the model's weights live at once downloaded, or None if
 * not cached yet.
 */
public func cachedModelPath(model: DemucsModel) -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_demucs_fn_func_cached_model_path(
        FfiConverterTypeDemucsModel_lower(model),$0
    )
})
}
/**
 * Override the model cache directory.
 *
 * On iOS/tvOS/visionOS call this once at app launch — before
 * `downloadModel` or `DemucsEngine.loadModel` — with a directory inside the
 * app sandbox, e.g. the app's Application Support or Caches directory.
 * The directory is created if missing.
 */
public func configureCacheDir(path: String)  {try! rustCall() {
    uniffi_demucs_fn_func_configure_cache_dir(
        FfiConverterString.lower(path),$0
    )
}
}
/**
 * Delete a model's weights from the local cache. Returns true if a file was
 * removed.
 */
public func deleteCachedModel(model: DemucsModel) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_demucs_fn_func_delete_cached_model(
        FfiConverterTypeDemucsModel_lower(model),$0
    )
})
}
/**
 * Whether the model's weights are already in the local cache.
 */
public func isModelCached(model: DemucsModel) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_demucs_fn_func_is_model_cached(
        FfiConverterTypeDemucsModel_lower(model),$0
    )
})
}
/**
 * Metadata (name, size, stems, download URL) for a model variant.
 */
public func modelMetadata(model: DemucsModel) -> ModelMetadata  {
    return try!  FfiConverterTypeModelMetadata_lift(try! rustCall() {
    uniffi_demucs_fn_func_model_metadata(
        FfiConverterTypeDemucsModel_lower(model),$0
    )
})
}
/**
 * Number of inference chunks a track of `n_samples` (per channel, at
 * 44100 Hz) is split into. Useful for sizing progress UIs.
 */
public func numChunks(nSamples: UInt64) -> UInt64  {
    return try!  FfiConverterUInt64.lift(try! rustCall() {
    uniffi_demucs_fn_func_num_chunks(
        FfiConverterUInt64.lower(nSamples),$0
    )
})
}
/**
 * Download a model's weights into the local cache.
 *
 * No-op (immediately reports `done`) if the model is already cached. Call
 * `configureCacheDir` first on sandboxed platforms.
 */
public func downloadModel(model: DemucsModel, listener: DownloadProgressListener)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_demucs_fn_func_download_model(FfiConverterTypeDemucsModel_lower(model),FfiConverterCallbackInterfaceDownloadProgressListener_lower(listener)
                )
            },
            pollFunc: ffi_demucs_rust_future_poll_void,
            completeFunc: ffi_demucs_rust_future_complete_void,
            freeFunc: ffi_demucs_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeDemucsFfiError_lift
        )
}
/**
 * `DemucsEngine.separate` with progress reporting and cancellation.
 *
 * A free function because UniFFI 0.31 only supports callback interfaces as
 * free-function parameters.
 */
public func separateWithProgress(engine: DemucsEngine, left: [Float], right: [Float], sampleRate: UInt32, listener: SeparationProgressListener)async throws  -> [StemResult]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_demucs_fn_func_separate_with_progress(FfiConverterTypeDemucsEngine_lower(engine),FfiConverterSequenceFloat.lower(left),FfiConverterSequenceFloat.lower(right),FfiConverterUInt32.lower(sampleRate),FfiConverterCallbackInterfaceSeparationProgressListener_lower(listener)
                )
            },
            pollFunc: ffi_demucs_rust_future_poll_rust_buffer,
            completeFunc: ffi_demucs_rust_future_complete_rust_buffer,
            freeFunc: ffi_demucs_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeStemResult.lift,
            errorHandler: FfiConverterTypeDemucsFfiError_lift
        )
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_demucs_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_demucs_checksum_func_all_models() != 40632) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_demucs_checksum_func_cached_model_path() != 59385) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_demucs_checksum_func_configure_cache_dir() != 33315) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_demucs_checksum_func_delete_cached_model() != 23501) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_demucs_checksum_func_is_model_cached() != 9391) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_demucs_checksum_func_model_metadata() != 64919) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_demucs_checksum_func_num_chunks() != 27500) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_demucs_checksum_func_download_model() != 37675) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_demucs_checksum_func_separate_with_progress() != 6510) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_demucs_checksum_method_demucsengine_is_loaded() != 28086) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_demucs_checksum_method_demucsengine_load_model() != 54613) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_demucs_checksum_method_demucsengine_loaded_model() != 45821) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_demucs_checksum_method_demucsengine_separate() != 52086) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_demucs_checksum_method_demucsengine_unload_model() != 24792) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_demucs_checksum_method_demucsengine_warmup() != 20811) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_demucs_checksum_constructor_demucsengine_new() != 51674) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_demucs_checksum_method_downloadprogresslistener_on_progress() != 44819) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_demucs_checksum_method_separationprogresslistener_on_progress() != 56005) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitDownloadProgressListener()
    uniffiCallbackInitSeparationProgressListener()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureDemucsInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all